// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MataKuliah struct {
	Kode                 string   `protobuf:"bytes,1,opt,name=kode,proto3" json:"kode,omitempty"`
	Nama                 string   `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	Sks                  int32    `protobuf:"varint,3,opt,name=sks,proto3" json:"sks,omitempty"`
	Dosen                string   `protobuf:"bytes,4,opt,name=dosen,proto3" json:"dosen,omitempty"`
	Semester             string   `protobuf:"bytes,5,opt,name=semester,proto3" json:"semester,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MataKuliah) Reset()         { *m = MataKuliah{} }
func (m *MataKuliah) String() string { return proto.CompactTextString(m) }
func (*MataKuliah) ProtoMessage()    {}
func (*MataKuliah) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *MataKuliah) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MataKuliah.Unmarshal(m, b)
}
func (m *MataKuliah) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MataKuliah.Marshal(b, m, deterministic)
}
func (m *MataKuliah) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MataKuliah.Merge(m, src)
}
func (m *MataKuliah) XXX_Size() int {
	return xxx_messageInfo_MataKuliah.Size(m)
}
func (m *MataKuliah) XXX_DiscardUnknown() {
	xxx_messageInfo_MataKuliah.DiscardUnknown(m)
}

var xxx_messageInfo_MataKuliah proto.InternalMessageInfo

func (m *MataKuliah) GetKode() string {
	if m != nil {
		return m.Kode
	}
	return ""
}

func (m *MataKuliah) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *MataKuliah) GetSks() int32 {
	if m != nil {
		return m.Sks
	}
	return 0
}

func (m *MataKuliah) GetDosen() string {
	if m != nil {
		return m.Dosen
	}
	return ""
}

func (m *MataKuliah) GetSemester() string {
	if m != nil {
		return m.Semester
	}
	return ""
}

type Krs struct {
	IdMahasiswa          int32         `protobuf:"varint,1,opt,name=id_mahasiswa,json=idMahasiswa,proto3" json:"id_mahasiswa,omitempty"`
	MataKuliahs          []*MataKuliah `protobuf:"bytes,2,rep,name=mata_kuliahs,json=mataKuliahs,proto3" json:"mata_kuliahs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Krs) Reset()         { *m = Krs{} }
func (m *Krs) String() string { return proto.CompactTextString(m) }
func (*Krs) ProtoMessage()    {}
func (*Krs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *Krs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Krs.Unmarshal(m, b)
}
func (m *Krs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Krs.Marshal(b, m, deterministic)
}
func (m *Krs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Krs.Merge(m, src)
}
func (m *Krs) XXX_Size() int {
	return xxx_messageInfo_Krs.Size(m)
}
func (m *Krs) XXX_DiscardUnknown() {
	xxx_messageInfo_Krs.DiscardUnknown(m)
}

var xxx_messageInfo_Krs proto.InternalMessageInfo

func (m *Krs) GetIdMahasiswa() int32 {
	if m != nil {
		return m.IdMahasiswa
	}
	return 0
}

func (m *Krs) GetMataKuliahs() []*MataKuliah {
	if m != nil {
		return m.MataKuliahs
	}
	return nil
}

type Response struct {
	Message              string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 uint64        `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	MataKuliahs          []*MataKuliah `protobuf:"bytes,3,rep,name=mata_kuliahs,json=mataKuliahs,proto3" json:"mata_kuliahs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMataKuliahs() []*MataKuliah {
	if m != nil {
		return m.MataKuliahs
	}
	return nil
}

func init() {
	proto.RegisterType((*MataKuliah)(nil), "proto.MataKuliah")
	proto.RegisterType((*Krs)(nil), "proto.Krs")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2)
}

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x37, 0xb1, 0xed, 0xa4, 0x50, 0x1d, 0x3c, 0x2c, 0x3d, 0xc5, 0x9c, 0x72, 0x6a,
	0xa1, 0xfa, 0x02, 0xea, 0x49, 0x42, 0x41, 0xf6, 0xe8, 0xc1, 0x32, 0x9a, 0xc1, 0x86, 0xb8, 0x49,
	0xc8, 0x44, 0xf4, 0xf1, 0x65, 0x37, 0x4d, 0x3d, 0x78, 0xe9, 0x69, 0xbe, 0x99, 0xdd, 0x65, 0xfe,
	0x8f, 0x85, 0x65, 0xdb, 0x35, 0x7d, 0xb3, 0xa1, 0xb6, 0x5c, 0x7b, 0xc2, 0xc8, 0x97, 0xf4, 0x07,
	0x60, 0x47, 0x3d, 0xe5, 0x5f, 0x9f, 0x25, 0x1d, 0x10, 0x21, 0xac, 0x9a, 0x82, 0x75, 0x90, 0x04,
	0xd9, 0xdc, 0x78, 0x76, 0xb3, 0x9a, 0x2c, 0xe9, 0xc9, 0x30, 0x73, 0x8c, 0x97, 0xa0, 0xa4, 0x12,
	0xad, 0x92, 0x20, 0x8b, 0x8c, 0x43, 0xbc, 0x86, 0xa8, 0x68, 0x84, 0x6b, 0x1d, 0xfa, 0x6b, 0x43,
	0x83, 0x2b, 0x98, 0x09, 0x5b, 0x96, 0x9e, 0x3b, 0x1d, 0xf9, 0x83, 0x53, 0x9f, 0xbe, 0x82, 0xca,
	0x3b, 0xc1, 0x1b, 0x58, 0x94, 0xc5, 0xde, 0xd2, 0x81, 0xa4, 0x94, 0x6f, 0xf2, 0xab, 0x23, 0x13,
	0x97, 0xc5, 0x6e, 0x1c, 0xe1, 0x1d, 0x2c, 0x2c, 0xf5, 0xb4, 0xaf, 0x7c, 0x48, 0xd1, 0x93, 0x44,
	0x65, 0xf1, 0xf6, 0x6a, 0x10, 0x59, 0xff, 0xc5, 0x37, 0xb1, 0x3d, 0xb1, 0xa4, 0x35, 0xcc, 0x0c,
	0x4b, 0xdb, 0xd4, 0xc2, 0xa8, 0x61, 0x6a, 0x59, 0x84, 0x3e, 0x46, 0xb5, 0xb1, 0x75, 0x76, 0xef,
	0xce, 0xd8, 0xd9, 0x85, 0xc6, 0xf3, 0xbf, 0x7d, 0xea, 0x9c, 0x7d, 0xdb, 0x0d, 0xa8, 0xfb, 0xe7,
	0x27, 0xcc, 0x60, 0xfe, 0xd8, 0x31, 0xf5, 0xec, 0xe4, 0xe0, 0xf8, 0x26, 0xef, 0x64, 0xb5, 0x3c,
	0xf2, 0x18, 0xea, 0x61, 0xfa, 0x32, 0xfc, 0xc1, 0xdb, 0x85, 0x2f, 0xb7, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb8, 0x35, 0x8f, 0x75, 0xa4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	CreateKrs(ctx context.Context, in *Krs, opts ...grpc.CallOption) (*Response, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateKrs(ctx context.Context, in *Krs, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.API/CreateKrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	CreateKrs(context.Context, *Krs) (*Response, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) CreateKrs(ctx context.Context, req *Krs) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKrs not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateKrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Krs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateKrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateKrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateKrs(ctx, req.(*Krs))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKrs",
			Handler:    _API_CreateKrs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
