// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain(in *jlexer.Lexer, out *payment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "isPay":
			out.IsPay = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain(out *jwriter.Writer, in payment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"isPay\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsPay))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v payment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v payment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *payment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *payment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain(l, v)
}
func easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain1(in *jlexer.Lexer, out *PaymentData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payment":
			(out.Payment).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain1(out *jwriter.Writer, in PaymentData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment\":"
		out.RawString(prefix[1:])
		(in.Payment).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComDinel13ThesisAcKrsDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComDinel13ThesisAcKrsDomain1(l, v)
}
